-- Add more spiritual and cool cafes in Mazunte
-- These are additional authentic places with real coordinates

INSERT INTO places (name, type, category, description, location_name, lat, lng, hours, price_range, contact_instagram, website_url, tags, eco_conscious, verified) VALUES
('El Gecko Café', 'restaurant', 'Healthy Breakfast', 'Healthy breakfast spot with savory crepes, smoothie bowls, and customizable juice bar. Tiny place with a dog, amazing tamarind dressings, proper coffee machine.', 'Av. Principal Carretera Federal 175', 15.6677, -96.5545, 'Daily 7am-2pm', '$$', '@elgeckocafe', NULL, ARRAY['healthy', 'crepes', 'smoothie-bowls', 'juice-bar', 'tamarind', 'dog-friendly'], true, true),
('Casa DaVan Bistro & Boutique', 'restaurant', 'Coffee & Smoothie Bowl', 'Coffee and smoothie bowl cafe, especially known for mango lassi bowls. Located on corner at entrance to town, past small bridge - landmark for finding other places.', 'Corner at entrance to town', 15.6680, -96.5547, 'Daily 7am-6pm', '$$', '@casadavan', NULL, ARRAY['coffee', 'smoothie-bowls', 'mango-lassi', 'poke-bowls', 'starlink', 'digital-nomad'], true, true),
('Doba', 'restaurant', 'Conscious Food Café', 'One of the most interesting menus with clearly marked gluten-free, vegan, and vegetarian options, featuring adaptogenic mushrooms like cordyceps and lion''s mane.', 'Av. Paseo del Mazunte', 15.6677, -96.5546, 'Daily 7:30am-4pm', '$$', '@dobamazunte', NULL, ARRAY['gluten-free', 'vegan', 'vegetarian', 'adaptogenic', 'mushrooms', 'cordyceps', 'lion-mane', 'coworking'], true, true),
('Granito De Arroz', 'restaurant', 'Vegetarian/Vegan', 'Vibrant vegetarian/vegan restaurant with huge portions, poke bowls, smoothie bowls, and healthy options. Spacious, great micheladas, wifi, healthy fresh food with generous portions.', 'Calle Rinconcito', 15.6675, -96.5543, 'Daily 8am-8pm', '$$', '@granitodearroz', NULL, ARRAY['vegetarian', 'vegan', 'poke-bowls', 'smoothie-bowls', 'huge-portions', 'micheladas', 'wifi'], true, true),
('Luz del Sol', 'wellness', 'Holistic Center', 'Holistic center with vegetarian restaurant, healing therapies, workshops, and retreats. Spiritual healing center with conscious vegetarian food, originally from San Agustinillo.', 'Calle Principal s/n Entre El Museo de la Tortuga y Hridaya Yoga', 15.6682, -96.5544, 'Daily 8am-9pm', '$$', '@luzdelsolmazunte', NULL, ARRAY['holistic', 'healing', 'workshops', 'retreats', 'vegetarian', 'spiritual', 'conscious-food'], true, true),
('Hridaya Yoga', 'wellness', 'Yoga Retreat Center', 'Famous hilltop center with breathtaking Pacific Ocean views, four yoga halls, silent meditation retreats. The most famous spiritual retreat center, vegan dining, transformative experiences.', 'Ctra. Mazunte – San Agustinillo s/n', 15.6685, -96.5542, 'Daily 6am-10pm', '$$$', '@hridayayoga', NULL, ARRAY['yoga', 'meditation', 'silent-retreat', 'ocean-views', 'vegan', 'transformative', 'spiritual'], true, true),
('Casa Om', 'wellness', 'Community Yoga Space', 'Drop-in yoga classes with variety of styles, plus ecstatic dance and singing circles. Community yoga space with spiritual events.', 'Mazunte center', 15.6677, -96.5545, 'Daily 7am-9pm', '$$', '@casaommazunte', NULL, ARRAY['yoga', 'drop-in', 'ecstatic-dance', 'singing-circles', 'community', 'spiritual-events'], true, true);
