-- Add organic stores and additional yoga/holistic centers in Mazunte
-- These are authentic health and wellness places with real coordinates

INSERT INTO places (name, type, category, description, location_name, lat, lng, hours, price_range, contact_phone, contact_instagram, website_url, tags, eco_conscious, verified) VALUES
('Yu''gupa Orgánica', 'community', 'Health Food Store', 'The biggest health food store in Mazunte with the most selection of supplements, superfoods, organic products, and grab-n-go vegan treats. Products include organic sunscreen, insect repellent, reusable nappies, biodegradable soaps/shampoos, essential oils & incense, dairy-free and organic gluten-free products, food supplements, superfoods, natural deodorant, facial serums.', 'Av Paseo del', 15.6677, -96.5545, 'Daily 8am-8pm', '$$', '+52 55 5818 5222', '@yugupaorganica', NULL, ARRAY['organic', 'supplements', 'superfoods', 'vegan', 'biodegradable', 'essential-oils', 'gluten-free', 'natural-cosmetics'], true, true),
('Cosméticos Naturales de Mazunte', 'community', 'Natural Cosmetics', 'Woman-owned community business producing high-quality natural, organic cosmetics with ecologically sound practices - they offer factory tours! Products include shampoos, soaps, moisturizers, reductive gels, lip balms, rose hip oil, coconut oil products, anti-wrinkle creams.', 'Av. Paseo del Mazunte esq. Ocotillo', 15.6678, -96.5546, 'Daily 9am-7pm', '$$', '958 587 4860', '@cosmeticosnaturalesmazunte', NULL, ARRAY['natural-cosmetics', 'organic', 'woman-owned', 'factory-tours', 'shampoo-bars', 'rose-hip-oil', 'coconut-oil', 'sustainable'], true, true),
('Tienda De Cosmeticos Mazunte', 'community', 'Natural Products', 'Carries tinctures and plant medicines. Natural products store with clean, high-quality products.', 'Main street', 15.6677, -96.5545, 'Daily 9am-6pm', '$$', NULL, '@tiendacosmeticosmazunte', NULL, ARRAY['tinctures', 'plant-medicines', 'natural-products', 'herbal'], true, true),
('Anáhuac', 'community', 'Natural Products Store', 'Natural products store with clean, high-quality shampoo bars, facial serums, natural deodorant. Limited selection but quality products.', 'Main area', 15.6677, -96.5545, 'Daily 9am-6pm', '$$', NULL, '@anahuacmazunte', NULL, ARRAY['shampoo-bars', 'facial-serums', 'natural-deodorant', 'quality-products'], true, true),
('Mercado Orgánico', 'community', 'Organic Farmers Market', 'Every Sunday 9:00am-3:00pm where you can buy organic produce. Weekly organic farmers market with fresh local produce.', 'Mazunte center', 15.6677, -96.5545, 'Sunday 9am-3pm', '$', NULL, '@mercadoorganicomazunte', NULL, ARRAY['organic-produce', 'farmers-market', 'fresh', 'local', 'sunday-market'], true, true),
('Uma Yoga', 'wellness', 'Luxury Yoga Retreat', 'Runs popular luxury beach wellness and yoga retreats with 2 hatha yoga classes daily, healthy meals, and beachfront accommodation at Hotel El Copal. Luxury yoga retreats in nature, chakra work, meditation.', 'Hotel El Copal, Calle del Panteón, Camino Mermejita s/n', 15.6670, -96.5535, 'Daily 6am-8pm', '$$$', NULL, '@umayogamazunte', NULL, ARRAY['luxury', 'beach-wellness', 'hatha-yoga', 'chakra-work', 'meditation', 'beachfront', 'retreats'], true, true),
('Zazil Retreat', 'wellness', 'Yoga Studio & Retreat', '170 m² yoga studio fully equipped, embedded in nature with ocean views, accommodates up to 16 people. Luxury retreat center with infinity pool and panoramic sea views.', 'San Agustinillo', 15.6700, -96.5520, 'Daily 6am-10pm', '$$$', NULL, '@zazilretreat', NULL, ARRAY['yoga-studio', 'ocean-views', 'nature', 'infinity-pool', 'panoramic', 'luxury', 'retreat-center'], true, true),
('Jojo Aquatic Bodywork', 'wellness', 'Water Therapy', 'Unique water therapy combining deep relaxation, stretching, and massage in open pool - weightless healing experience. Over 10 years experience, also offers couples retreats.', 'Mazunte area', 15.6677, -96.5545, 'By appointment', '$$$', NULL, '@jojoaquaticbodywork', NULL, ARRAY['water-therapy', 'deep-relaxation', 'stretching', 'massage', 'weightless', 'healing', 'couples-retreats'], true, true);
